### ISSUE TITLE
User can click on a Category and go to a page for the Category that shows its Resources

### ISSUE THREAD

**Issue by francisli** [dev-mission/sfdreamer#40]

**Comment by francisli** [comment]
Let's have the URLs for the cards link to:

/categories/{category.slug}

So if the category slug is education, the url will be:

/categories/education

**Comment by GaelGil** [comment]
> Let's have the URLs for the cards link to:
> 
> /categories/{category.slug}
> 
> So if the category slug is education, the url will be:
> 
> /categories/education

Would we need to pass in the `category.id` as well to access that specific categories resources or is there a way to do this without the id?
